-- JUST MAKE YOUR DISTRIBUTION FILES LIKE THIS AND THEY WILL WORK
-- PEOPLE REGULARLY FUCK UP THE SPAWNING OF BOTH VANILLA AND OTHER MOD ITEMS WITH BAD DISTRBUTION FILES

-- YES, YOU WILL SEE PEOPLE DO ITEM SPAWNING DIFFERENTLY IN OTHER MODS ON THE WORKSHOP
-- IN SOME OF THOSE CASE, YES THEY WILL WORK
-- IN MANY OTHER CASES THEY ARE FUCKING UP THE SPAWNING OF VANILLA AND/OR OTHER MOD ITEMS
-- THIS IS JUST AN EXAMPLE OF THE SIMPLEST WAY TO SPAWN NEW ITEMS THAT WILL WORK

-- DON'T JUST CUT AND PASTE THE ITEM SPAWNING FILES FROM OTHER MODS AND SWAP IN YOUR ITEMS
-- THIS IS HOW FUCKUPS ARE SPREAD AROUND

-- FOR THE LOVE OF PETE ABSOLUTELY DO NOT HAVE YOUR DISTRIBUTION FILES NAMED "Distributions.lua", "ProceduralDistributions.lua", or "VehicleDistributions.lua"
-- I SEE THIS ^ ALL THE TIME AND THAT ABSOLUTELY DOES FUCK UP BOTH VANILLA AND OTHER MOD ITEM SPAWNING

-- PUT YOUR DISTRIBUTION FILE IN THE "\media\lua\Server" DIRECTORY IN YOUR MOD FOLDER
--

require 'Items/SuburbsDistributions'
require "Items/ProceduralDistributions" -- YES ONE USES '' THE OTHERS USE "", THEY BOTH WORK
require "Vehicles/VehicleDistributions"
-- THIS ^ ISN'T ALWAYS NECESSARY, BUT IT SOLVES LOAD ORDER ISSUES AND WILL CAUSE NO ISSUES IF IT'S NOT NECESSARY
-- DON'T FUSS OVER IT JUST USE THE REQURIES IF YOU WANT YOUR SHIT TO WORK PRORERLY

-- YOU WILL SEE PEOPLE USING "rolls" VALUES IN THE DISTRIBUTION FILES IN THEIR MODS
-- THAT IS ONE WAY THAT PEOPLE FUCK UP ITEM SPAWNING OF VANILLA AND OTHER MOD ITEMS
-- YOU ONLY NEED TO DEFINE "rolls" VALUES WHEN MAKING NEW DISTRIBUTION TABLES FOR NEW CONTAINERS AND ROOMDEF/CONTAINER COMBIANTIONS
-- IF YOU DON'T KNOW WHAT THAT MEANS, YOU DON'T NEED TO USE ROLLS

-- SOME OF THESE EXAMPLES MAY USE TABLES THAT WILL BECOME PHASED OUT IN FUTURE IMPROVEMENTS TO VANILLA ITEM SPAWNING
-- IT'S THE FORMATTING THAT'S IMPORTANT, NOT THE SPECIFIC TABLES BEING REFERENCED

-- USE THE FOLLOWING EXAMPLES FOR HOW TO ADD ITEM SPAWNS TO THE LOOT TABLES IN "Distributions.lua"

table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Base.BlairsBestItem")
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.1)
 -- ALTHOUGH THE SECOND VALUE DICTATES THE SPAWN CHANCE OF AN ITEM IT'S NOT A PERCENTAGE
 -- THERE IS ALL SORTS OF CONVOLUTED MATH BEING USED FOR THE SPAWN CHANCE CALCULATION
 -- JUST USE A VALUE FROM THE VANILLA TABLES THAT APPROXIMATES THE CHANCE THAT YOU WANT YOU ITEMS TO SPAWN
 
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "BlairsBestItem")
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.1)
-- IF AN ITEM IS IN THE MODULE "Base" IT DOESN'T NEED TO HAVE "Base." IN THE NAME WHEN ADDED TO THE TABLES
-- BUT IT ALSO CAUSE NO ISSUES IF IT DOES HAVE "Base." IN THERE

table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Filibuster.FilibustersBestItem")
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.1)
-- WHEN AN ITEM IS NOT IN MODULE "Base" THEN YOU DO NEED TO INCLUDE IT'S MODULE WITH IT'S NAME WHEN ADDING IT TO THE TABLES

table.insert(SuburbsDistributions.all.sidetable.items, "Base.BlairsBestItem");
table.insert(SuburbsDistributions.all.sidetable.items, 2);
-- HOLY FUCK, THE FORMATTING OF THIS EXAMPLE IF DIFFERENT THAN THE OTHER EXAMPLES?!?!?
-- BOTH WAYS WILL WORK, YOU CAN DO IT EITHER WAY, I DON'T PRETEND TO UNDERSTAND THIS SHIT

table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, "Base.BlairsBestItem");
table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, 10);
-- YES THIS THIRD EXAMPLE IS DIFFERENT THAN THE PREVIOUS TWO EXAMPLES
-- THAT IS BECAUSE ADDING ITEMS TO THE CONTAINERS THAT CAN SPAWN IN OTHER CONTAINERS, SUCH AS BACKPACKS, IS DIFFERENT THAN ADDING ITEMS TO ROOMDEF/CONTAINER COMBINATIONS
--

-- USE THE FOLLOWING EXMAPLES FOR HOW TO ADD ITEM SPAWNS TO THE LOOT TABLES IN "ProceduralDistributions.lua"

table.insert(ProceduralDistributions.list["KitchenRandom"].items, "Base.BlairsBestItem")
table.insert(ProceduralDistributions.list["KitchenRandom"].items, 0.1)

table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "Base.BlairsBestItem");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
-- WHY DO THE ABOVE TABLES FOR PProceduralDistributions HAVE 'list' IN THERE?
-- I HAVE NO IDEA, I JUST KNOW YOU NEED IT FOR THEM TO WORK
--

-- USE THE FOLLOWING EXAMPLES FOR HOW TO ADD ITEM SPAWNS TO THE LOOT TABLES IN "VehicleDistributions.lua"

table.insert(VehicleDistributions["GloveBox"].items, "Base.BlairsBestItem")
table.insert(VehicleDistributions["GloveBox"].items, 0.1)

table.insert(VehicleDistributions["SurvivalistTruckBed"].items, "Base.BlairsBestItem");
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, 1);
--

-- THIS IS HOW YOU DEFINE A TABLE FOR A NEW CONTAINER ITEM SUCH AS NEW BAGS

SuburbsDistributions["Bag_AlgolsBetterBag"] = {
	rolls = 1, -- "rolls" DICTATES THE NUMBER OF TIMES THE ITEM SPAWNING RNG CHECKS TO SEE IF AN ITEM SPAWNS; ONLY USE IT WHEN MAKING NEW TABLES
	items = {
	"Base.BlairsBestItem", 2,
	},
	fillRand = 0, -- I DON'T KNOW WHAT THIS VALUE DOES, IT'S JUST USED IN THE VANILLA TABLES FOR ALMOST ALL BAGS
}
--
	
-- THIS IS HOW YOU DEFINE A TABLE FOR A NEW Roomdef/container combinations
-- YOU ONLY NEED THIS WHEN MAKING NEW Roomdefs WITH BUILDINGS FOR MAPS
-- IF YOU DON'T UNDERSTAND WHAT THAT MEANS THEN YOU DON'T NEED TO WORRY ABOUT IT

SuburbsDistributions["blairsboudoir"] = {
        sidetable =
        {
            rolls = 5, 
            items = {
                "Base.BlairsBestItem", 3,
            }
        },
        all = -- "all" ADDS THE ITEM SPAWNING TO ALL CONTAINERS THAT ARE NOT DEFINED ABOVE
        {
            rolls = 5,
            items = {
                "Base.BlairsBestItem", 3,
            }
        },
}

-- JUST DO YOUR ITEM SPAWNING FILES LIKE THIS AND THEY WILL WORK WITHOUT FUCKING UP THE SPAWNING OF YOUR ITEMS, VANILLA ITEMS, OR ITEMS IN OTHER MODS
-- HAVING SAID THAT, ALWAYS TEST YOUR MODS AND MAKE SURE THEY'RE WORKING PROPERLY WITHOUT ISSUES BEFORE UPLOADING THEM TO THE WORKSHOP
-- YOU HAVE TO PUT IN THE TIME AND THE WORK TESTING STUFF IF YOU WANT IT TO WORK PROPERLY

-- ALSO BE AWARE THAT PEOPLE WILL REPORT YOUR ITEM SPAWNING BEING BROKEN IF THEY CAN'T FIND YOUR MOD ITEM IN THEIR SPAWN HOUSE OR WITHIN 5 MINUTES
-- THE MORE THEY WANT THE ITEM, THE MORE LIKELY YOU WILL GET FALSE REPORTS OF THAT NATURE
-- THEY COULD ALSO BE USING ONE OF THE MANY, MANY MODS THAT FUCKS UP ITEM SPAWNING
-- IF THE ITEM SPAWNING WORKS WITHOUT ANY ERROR NOTIFICATIONS WHEN YOU TEST YOUR MOD USING NO OTHER MODS THEN YOU WILL KNOW THAT YOU DID YOUR ITEM SPAWNING PROPERLY

-- BE AWARE THAT THE IMPROVEMENTS TO THE ITEM SPAWNING METHODS IN VANILLA PZ IS STILL ONGOING
-- THAT MEANS THAT THE SPECIFICS OF THE ABOVE EXAMPLE MAY BECOME OBSOLETE
-- IT'S THE FORMATTING THAT'S IMPORTANT, NOT THE SPECIFICS
-- ALSO THIS MEANS THAT YOU PROBABLY WILL NEED TO UPDATE THE ITEM SPAWNING FILES IN YOUR MODS WITH EVERY UPDATE TO PZ THAT INCLUDES THE ITEM SPAWNING IMPROVEMENTS
-- WAIT UNTIL BUILD 41 IS STABLE IF YOU DON'T WANT TO DEAL WITH THAT; IT IS INDEED A GODDAMN HEADACHE

-- I'M NEITHER SMART NOR DO I PRETEND TO UNDERSTAND THIS SHIT
-- THE ABOVE EXAMPLES JUST WORK; I'M UNABLE TO ANSWER A MILLION FUSSY QUESTIONS ABOUT THE MINUTIA AND TECHNICAL DETAILS OF THE ABOVE EXAMPLES